name: Build and deploy JAR app to Azure Web App - metrosys

on:
  push:
    branches:
      - metro-be
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

      - name: Build with Maven
        run: mvn clean install
        working-directory: metro-system

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: metro-system/target/*.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app
          path: java-app  # ✅ Quan trọng

      - name: List downloaded files
        run: ls -al java-app  # ✅ Kiểm tra file thực sự tồn tại

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_007F9E1103E24800812A93222A2B6293 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_350C2743A93F4D1E92809D047188BC48 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_56AA446666AF4CF797F5278E29E2E217 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'metrosys'
          slot-name: 'Production'
          package: java-app/*.jar
